#!/usr/bin/env bash
#script that transfers a file from my client to my server
#to remember for task 1: ./0-transfer_file 1-install_nginx_web_server 18.206.198.128 ubuntu /home/vorg/.ssh/school
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
