#!/usr/bin/env bash
# script that install nginx web server, set a directory and create a file with hello world inside
sudo apt-get -y update
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
sudo sed -i '/server {/a location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default
sudo service nginx restart
