#!/usr/bin/env bash
# script that set a custom header named 'X-Served-By' in my 2nd server
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

redirect_link="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/thevorgx permanent;"
sudo sed -i "s/server_name _;/$redirect_link/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
redirect_link="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$redirect_link/" /etc/nginx/sites-enabled/default

cust_header="add_header X-Served-By \$hostname;"
sudo sed -i "/server_name _/a $cust_header" /etc/nginx/sites-enabled/default
sudo service nginx restart
