#!/usr/bin/env bash
# script that set a custom header named 'X-Served-By' in my 2nd server
cust_header="add_header X-Served-By \$hostname;"
echo "$cust_header" | sudo tee -a /etc/nginx/sites-enabled/default >/dev/null
sudo service nginx restart
