#!/usr/bin/env bash
hours=1
minutes=0
echo "Hour: $minutes"
((minutes++))
while [ "$minutes" -le 59 ]
do
    echo "$minutes"
    (( minutes++ ))
done

echo "Hour: $hours"
while [ "$hours" -le 12 ]
do
    echo "$hours"
    ((hours++))
done
