#!/usr/bin/env bash
# for the host ip, first, Set the path to the private key, after that set password authentication to no
Host 54.237.118.2
    IdentityFile ~/.ssh/school
    PreferredAuthentications publickey
    PasswordAuthentication no
